### ISSUE TITLE
Redesign sourcing steps list/grid

### ISSUE THREAD

**Issue by eltazy** [KadeaAcademy/kda-snoop-sourcing#128]
Changer le texte et design de la liste des étapes d'un sourcing

## Sub-tasks

- [ ] Add a title
- [ ] Align items uniformement
- [ ] [Change list item front icon](https://github.com/KadeaAcademy/kda-snoop-sourcing/issues/126)
- [ ] Hide step button instead of changing status
- [ ] [Update popup text for timed steps](https://github.com/KadeaAcademy/kda-snoop-sourcing/issues/127)
